apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-demo
  namespace: argocd
spec:
  project: default
  source:
    chart: podinfo
    repoURL: https://stefanprodan.github.io/podinfo
    targetRevision: 6.6.2
    helm:
      parameters:
        - name: replicaCount
          value: "3"
        - name: ui.color
          value: "#34577c"
        - name: service.type
          value: "LoadBalancer"
        - name: service.externalPort
          value: "9898"
        - name: priorityClassName
          value: "app-low-priority"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
